project:
  type: book

book:
  title: "Statistical Rethinking"
  author: "Eric Book"
  date: "6/05/2023"
  favicon: images/sr-favicon-32.png
  reader-mode: true
  repo-url: https://github.com/ercbk/Statistical-Rethinking-Notebook
  page-footer:
    background: "#fffaf0"
    foreground: "#1E4477"
    center: 
      - href: LICENSE.qmd
  sidebar: 
    collapse-level: 1
    background: "#fffaf0"
    foreground: "#1E4477"
    tools: 
      - icon: house-fill
        href: https://ericbook.netlify.app/
      - icon: database-fill-gear
        href: https://ercbk.github.io/Data-Science-Notebook/
  chapters:
    - index.qmd
    - qmd/chapter-summaries.qmd
    - qmd/chapter-2.qmd
    - qmd/chapter-3.qmd
    - qmd/statistical-rethinking.qmd
    - qmd/glossary.qmd

format:
  html:
    theme: paper
    css: styles.css
    code-link: true
    backgroundcolor: "#fffaf0"
    fontcolor: "#404d59"
    mainfont: 'Lora'
    monofont: 'Fira Code Retina'
    linkcolor: '#0064B6FF'
    highlight-style: printing

editor: visual

execute:
    freeze: auto
